packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
